project:
  type: book
  output-dir: _book
  execute-dir: project

book:
  title: "MVM Elephants"
  reader-mode: true

  #site-url: 
  #repo-url: 
  #repo-branch: main
  chapters:
    - index.qmd
    - code/vonmises_distribution.qmd
    - code/preparazione_dati.qmd
    - code/GON09.qmd

format:
  html:
    code-fold: true

execute:
  cache: true
  warning: false
  message: false